/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JTextField;

/**
 * Interfaz Gráfica de Usuario que representa la solución del problema de 
 * 8-reinas 
 * @author Karen Artega Mendoza 190161, Uxia Vázquez Fernández 190940
 */
public class Reinas extends javax.swing.JFrame {
    /**
     * tablero tipo JTextField que hace referencia a las celdas de un 
     * tabero de ajedrez
     * 
     */
    private JTextField [][] tablero;

    /**
     * Constructor
     * inicializa componentes del JFrame
     * inicializa variable tablero 
     * llena cada celda de la matriz <code>tablero</code> con una componente JTextField
     */
    public Reinas() {
        initComponents();
        tablero= new JTextField[8][8];
        llenarTablero();
    }
    /**
     * método que asigna una variable tipo <code>JTextField</code> a cada una de las 
     * celdas de la matriz tablero
     */
    private void llenarTablero(){
        tablero[0][0]= txt00;
        tablero[0][1]= txt01;
        tablero[0][2]= txt02;
        tablero[0][3]= txt03;
        tablero[0][4]= txt04;
        tablero[0][5]= txt05;
        tablero[0][6]= txt06;
        tablero[0][7]= txt07;
        tablero[1][0]= txt10;
        tablero[1][1]= txt11;
        tablero[1][2]= txt12;
        tablero[1][3]= txt13;
        tablero[1][4]= txt14;
        tablero[1][5]= txt15;
        tablero[1][6]= txt16;
        tablero[1][7]= txt17;
        tablero[2][0]= txt20;
        tablero[2][1]= txt21;
        tablero[2][2]= txt22;
        tablero[2][3]= txt23;
        tablero[2][4]= txt24;
        tablero[2][5]= txt25;
        tablero[2][6]= txt26;
        tablero[2][7]= txt27;
        tablero[3][0]= txt30;
        tablero[3][1]= txt31;
        tablero[3][2]= txt32;
        tablero[3][3]= txt33;
        tablero[3][4]= txt34;
        tablero[3][5]= txt35;
        tablero[3][6]= txt36;
        tablero[3][7]= txt37;
        tablero[4][0]= txt40;
        tablero[4][1]= txt41;
        tablero[4][2]= txt42;
        tablero[4][3]= txt43;
        tablero[4][4]= txt44;
        tablero[4][5]= txt45;
        tablero[4][6]= txt46;
        tablero[4][7]= txt47;
        tablero[5][0]= txt50;
        tablero[5][1]= txt51;
        tablero[5][2]= txt52;
        tablero[5][3]= txt53;
        tablero[5][4]= txt54;
        tablero[5][5]= txt55;
        tablero[5][6]= txt56;
        tablero[5][7]= txt57;
        tablero[6][0]= txt60;
        tablero[6][1]= txt61;
        tablero[6][2]= txt62;
        tablero[6][3]= txt63;
        tablero[6][4]= txt64;
        tablero[6][5]= txt65;
        tablero[6][6]= txt66;
        tablero[6][7]= txt67;
        tablero[7][0]= txt70;
        tablero[7][1]= txt71;
        tablero[7][2]= txt72;
        tablero[7][3]= txt73;
        tablero[7][4]= txt74;
        tablero[7][5]= txt75;
        tablero[7][6]= txt76;
        tablero[7][7]= txt77;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        txtFila = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        board = new java.awt.Panel();
        txt00 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt01 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt02 = new javax.swing.JTextField();
        txt03 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt04 = new javax.swing.JTextField();
        txt05 = new javax.swing.JTextField();
        txt06 = new javax.swing.JTextField();
        txt07 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt15 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt30 = new javax.swing.JTextField();
        txt31 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt32 = new javax.swing.JTextField();
        txt33 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt34 = new javax.swing.JTextField();
        txt35 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        txt26 = new javax.swing.JTextField();
        txt36 = new javax.swing.JTextField();
        txt37 = new javax.swing.JTextField();
        txt27 = new javax.swing.JTextField();
        txt65 = new javax.swing.JTextField();
        txt66 = new javax.swing.JTextField();
        txt52 = new javax.swing.JTextField();
        txt76 = new javax.swing.JTextField();
        txt44 = new javax.swing.JTextField();
        txt77 = new javax.swing.JTextField();
        txt45 = new javax.swing.JTextField();
        txt67 = new javax.swing.JTextField();
        txt46 = new javax.swing.JTextField();
        txt47 = new javax.swing.JTextField();
        txt57 = new javax.swing.JTextField();
        txt56 = new javax.swing.JTextField();
        txt55 = new javax.swing.JTextField();
        txt54 = new javax.swing.JTextField();
        txt60 = new javax.swing.JTextField();
        txt70 = new javax.swing.JTextField();
        txt71 = new javax.swing.JTextField();
        txt61 = new javax.swing.JTextField();
        txt62 = new javax.swing.JTextField();
        txt72 = new javax.swing.JTextField();
        txt40 = new javax.swing.JTextField();
        txt73 = new javax.swing.JTextField();
        txt50 = new javax.swing.JTextField();
        txt63 = new javax.swing.JTextField();
        txt41 = new javax.swing.JTextField();
        txt64 = new javax.swing.JTextField();
        txt51 = new javax.swing.JTextField();
        txt74 = new javax.swing.JTextField();
        txt42 = new javax.swing.JTextField();
        txt75 = new javax.swing.JTextField();
        txt43 = new javax.swing.JTextField();
        txt53 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtCol = new javax.swing.JTextField();
        label1 = new java.awt.Label();

        label2.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(487, 571));

        txtFila.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilaActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("1");
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 30));

        lbl.setFont(lbl.getFont());
        lbl.setText("Fila de la primera reina:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("6");
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 30));

        board.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        board.setPreferredSize(new java.awt.Dimension(400, 400));

        txt00.setEditable(false);
        txt00.setBackground(new java.awt.Color(204, 153, 255));
        txt00.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt00.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt00.setPreferredSize(new java.awt.Dimension(50, 50));
        txt00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt00ActionPerformed(evt);
            }
        });

        txt10.setEditable(false);
        txt10.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt10.setPreferredSize(new java.awt.Dimension(50, 50));
        txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt10ActionPerformed(evt);
            }
        });

        txt01.setEditable(false);
        txt01.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt01.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt01.setPreferredSize(new java.awt.Dimension(50, 50));
        txt01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt01ActionPerformed(evt);
            }
        });

        txt11.setEditable(false);
        txt11.setBackground(new java.awt.Color(204, 153, 255));
        txt11.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt11.setPreferredSize(new java.awt.Dimension(50, 50));

        txt02.setEditable(false);
        txt02.setBackground(new java.awt.Color(204, 153, 255));
        txt02.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt02.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt02.setPreferredSize(new java.awt.Dimension(50, 50));
        txt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt02ActionPerformed(evt);
            }
        });

        txt03.setEditable(false);
        txt03.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt03.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt03.setPreferredSize(new java.awt.Dimension(50, 50));
        txt03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt03ActionPerformed(evt);
            }
        });

        txt13.setEditable(false);
        txt13.setBackground(new java.awt.Color(204, 153, 255));
        txt13.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt13.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt13.setPreferredSize(new java.awt.Dimension(50, 50));

        txt12.setEditable(false);
        txt12.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt12.setPreferredSize(new java.awt.Dimension(50, 50));
        txt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt12ActionPerformed(evt);
            }
        });

        txt04.setEditable(false);
        txt04.setBackground(new java.awt.Color(204, 153, 255));
        txt04.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt04.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt04.setPreferredSize(new java.awt.Dimension(50, 50));
        txt04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt04ActionPerformed(evt);
            }
        });

        txt05.setEditable(false);
        txt05.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt05.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt05.setPreferredSize(new java.awt.Dimension(50, 50));
        txt05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt05ActionPerformed(evt);
            }
        });

        txt06.setEditable(false);
        txt06.setBackground(new java.awt.Color(204, 153, 255));
        txt06.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt06.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt06.setPreferredSize(new java.awt.Dimension(50, 50));
        txt06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt06ActionPerformed(evt);
            }
        });

        txt07.setEditable(false);
        txt07.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt07.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt07.setPreferredSize(new java.awt.Dimension(50, 50));
        txt07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt07ActionPerformed(evt);
            }
        });

        txt17.setEditable(false);
        txt17.setBackground(new java.awt.Color(204, 153, 255));
        txt17.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt17.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt17.setPreferredSize(new java.awt.Dimension(50, 50));

        txt16.setEditable(false);
        txt16.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt16.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt16.setPreferredSize(new java.awt.Dimension(50, 50));
        txt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt16ActionPerformed(evt);
            }
        });

        txt15.setEditable(false);
        txt15.setBackground(new java.awt.Color(204, 153, 255));
        txt15.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt15.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt15.setPreferredSize(new java.awt.Dimension(50, 50));

        txt14.setEditable(false);
        txt14.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt14.setPreferredSize(new java.awt.Dimension(50, 50));
        txt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt14ActionPerformed(evt);
            }
        });

        txt20.setEditable(false);
        txt20.setBackground(new java.awt.Color(204, 153, 255));
        txt20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt20.setPreferredSize(new java.awt.Dimension(50, 50));
        txt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt20ActionPerformed(evt);
            }
        });

        txt30.setEditable(false);
        txt30.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt30.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt30.setPreferredSize(new java.awt.Dimension(50, 50));
        txt30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt30ActionPerformed(evt);
            }
        });

        txt31.setEditable(false);
        txt31.setBackground(new java.awt.Color(204, 153, 255));
        txt31.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt31.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt31.setPreferredSize(new java.awt.Dimension(50, 50));

        txt21.setEditable(false);
        txt21.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt21.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt21.setPreferredSize(new java.awt.Dimension(50, 50));
        txt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt21ActionPerformed(evt);
            }
        });

        txt22.setEditable(false);
        txt22.setBackground(new java.awt.Color(204, 153, 255));
        txt22.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt22.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt22.setPreferredSize(new java.awt.Dimension(50, 50));
        txt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt22ActionPerformed(evt);
            }
        });

        txt32.setEditable(false);
        txt32.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt32.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt32.setPreferredSize(new java.awt.Dimension(50, 50));
        txt32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt32ActionPerformed(evt);
            }
        });

        txt33.setEditable(false);
        txt33.setBackground(new java.awt.Color(204, 153, 255));
        txt33.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt33.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt33.setPreferredSize(new java.awt.Dimension(50, 50));
        txt33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt33ActionPerformed(evt);
            }
        });

        txt23.setEditable(false);
        txt23.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt23.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt23.setPreferredSize(new java.awt.Dimension(50, 50));
        txt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt23ActionPerformed(evt);
            }
        });

        txt24.setEditable(false);
        txt24.setBackground(new java.awt.Color(204, 153, 255));
        txt24.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt24.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt24.setPreferredSize(new java.awt.Dimension(50, 50));
        txt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt24ActionPerformed(evt);
            }
        });

        txt34.setEditable(false);
        txt34.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt34.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt34.setPreferredSize(new java.awt.Dimension(50, 50));
        txt34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt34ActionPerformed(evt);
            }
        });

        txt35.setEditable(false);
        txt35.setBackground(new java.awt.Color(204, 153, 255));
        txt35.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt35.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt35.setPreferredSize(new java.awt.Dimension(50, 50));

        txt25.setEditable(false);
        txt25.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt25.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt25.setPreferredSize(new java.awt.Dimension(50, 50));
        txt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt25ActionPerformed(evt);
            }
        });

        txt26.setEditable(false);
        txt26.setBackground(new java.awt.Color(204, 153, 255));
        txt26.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt26.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt26.setPreferredSize(new java.awt.Dimension(50, 50));
        txt26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt26ActionPerformed(evt);
            }
        });

        txt36.setEditable(false);
        txt36.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt36.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt36.setPreferredSize(new java.awt.Dimension(50, 50));
        txt36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt36ActionPerformed(evt);
            }
        });

        txt37.setEditable(false);
        txt37.setBackground(new java.awt.Color(204, 153, 255));
        txt37.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt37.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt37.setPreferredSize(new java.awt.Dimension(50, 50));

        txt27.setEditable(false);
        txt27.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt27.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt27.setPreferredSize(new java.awt.Dimension(50, 50));
        txt27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt27ActionPerformed(evt);
            }
        });

        txt65.setEditable(false);
        txt65.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt65.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt65.setPreferredSize(new java.awt.Dimension(50, 50));
        txt65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt65ActionPerformed(evt);
            }
        });

        txt66.setEditable(false);
        txt66.setBackground(new java.awt.Color(204, 153, 255));
        txt66.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt66.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt66.setPreferredSize(new java.awt.Dimension(50, 50));
        txt66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt66ActionPerformed(evt);
            }
        });

        txt52.setEditable(false);
        txt52.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt52.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt52.setPreferredSize(new java.awt.Dimension(50, 50));
        txt52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt52ActionPerformed(evt);
            }
        });

        txt76.setEditable(false);
        txt76.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt76.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt76.setPreferredSize(new java.awt.Dimension(50, 50));
        txt76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt76ActionPerformed(evt);
            }
        });

        txt44.setEditable(false);
        txt44.setBackground(new java.awt.Color(204, 153, 255));
        txt44.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt44.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt44.setPreferredSize(new java.awt.Dimension(50, 50));
        txt44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt44ActionPerformed(evt);
            }
        });

        txt77.setEditable(false);
        txt77.setBackground(new java.awt.Color(204, 153, 255));
        txt77.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt77.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt77.setPreferredSize(new java.awt.Dimension(50, 50));

        txt45.setEditable(false);
        txt45.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt45.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt45.setPreferredSize(new java.awt.Dimension(50, 50));
        txt45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt45ActionPerformed(evt);
            }
        });

        txt67.setEditable(false);
        txt67.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt67.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt67.setPreferredSize(new java.awt.Dimension(50, 50));
        txt67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt67ActionPerformed(evt);
            }
        });

        txt46.setEditable(false);
        txt46.setBackground(new java.awt.Color(204, 153, 255));
        txt46.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt46.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt46.setPreferredSize(new java.awt.Dimension(50, 50));
        txt46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt46ActionPerformed(evt);
            }
        });

        txt47.setEditable(false);
        txt47.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt47.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt47.setPreferredSize(new java.awt.Dimension(50, 50));
        txt47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt47ActionPerformed(evt);
            }
        });

        txt57.setEditable(false);
        txt57.setBackground(new java.awt.Color(204, 153, 255));
        txt57.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt57.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt57.setPreferredSize(new java.awt.Dimension(50, 50));

        txt56.setEditable(false);
        txt56.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt56.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt56.setPreferredSize(new java.awt.Dimension(50, 50));
        txt56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt56ActionPerformed(evt);
            }
        });

        txt55.setEditable(false);
        txt55.setBackground(new java.awt.Color(204, 153, 255));
        txt55.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt55.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt55.setPreferredSize(new java.awt.Dimension(50, 50));

        txt54.setEditable(false);
        txt54.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt54.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt54.setPreferredSize(new java.awt.Dimension(50, 50));
        txt54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt54ActionPerformed(evt);
            }
        });

        txt60.setEditable(false);
        txt60.setBackground(new java.awt.Color(204, 153, 255));
        txt60.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt60.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt60.setPreferredSize(new java.awt.Dimension(50, 50));
        txt60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt60ActionPerformed(evt);
            }
        });

        txt70.setEditable(false);
        txt70.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt70.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt70.setPreferredSize(new java.awt.Dimension(50, 50));
        txt70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt70ActionPerformed(evt);
            }
        });

        txt71.setEditable(false);
        txt71.setBackground(new java.awt.Color(204, 153, 255));
        txt71.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt71.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt71.setPreferredSize(new java.awt.Dimension(50, 50));

        txt61.setEditable(false);
        txt61.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt61.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt61.setPreferredSize(new java.awt.Dimension(50, 50));
        txt61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt61ActionPerformed(evt);
            }
        });

        txt62.setEditable(false);
        txt62.setBackground(new java.awt.Color(204, 153, 255));
        txt62.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt62.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt62.setPreferredSize(new java.awt.Dimension(50, 50));
        txt62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt62ActionPerformed(evt);
            }
        });

        txt72.setEditable(false);
        txt72.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt72.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt72.setPreferredSize(new java.awt.Dimension(50, 50));
        txt72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt72ActionPerformed(evt);
            }
        });

        txt40.setEditable(false);
        txt40.setBackground(new java.awt.Color(204, 153, 255));
        txt40.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt40.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt40.setPreferredSize(new java.awt.Dimension(50, 50));
        txt40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt40ActionPerformed(evt);
            }
        });

        txt73.setEditable(false);
        txt73.setBackground(new java.awt.Color(204, 153, 255));
        txt73.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt73.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt73.setPreferredSize(new java.awt.Dimension(50, 50));

        txt50.setEditable(false);
        txt50.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt50.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt50.setPreferredSize(new java.awt.Dimension(50, 50));
        txt50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt50ActionPerformed(evt);
            }
        });

        txt63.setEditable(false);
        txt63.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt63.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt63.setPreferredSize(new java.awt.Dimension(50, 50));
        txt63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt63ActionPerformed(evt);
            }
        });

        txt41.setEditable(false);
        txt41.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt41.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt41.setPreferredSize(new java.awt.Dimension(50, 50));
        txt41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt41ActionPerformed(evt);
            }
        });

        txt64.setEditable(false);
        txt64.setBackground(new java.awt.Color(204, 153, 255));
        txt64.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt64.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt64.setPreferredSize(new java.awt.Dimension(50, 50));
        txt64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt64ActionPerformed(evt);
            }
        });

        txt51.setEditable(false);
        txt51.setBackground(new java.awt.Color(204, 153, 255));
        txt51.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt51.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt51.setPreferredSize(new java.awt.Dimension(50, 50));

        txt74.setEditable(false);
        txt74.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt74.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt74.setPreferredSize(new java.awt.Dimension(50, 50));
        txt74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt74ActionPerformed(evt);
            }
        });

        txt42.setEditable(false);
        txt42.setBackground(new java.awt.Color(204, 153, 255));
        txt42.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt42.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt42.setPreferredSize(new java.awt.Dimension(50, 50));
        txt42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt42ActionPerformed(evt);
            }
        });

        txt75.setEditable(false);
        txt75.setBackground(new java.awt.Color(204, 153, 255));
        txt75.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt75.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt75.setPreferredSize(new java.awt.Dimension(50, 50));

        txt43.setEditable(false);
        txt43.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt43.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt43.setPreferredSize(new java.awt.Dimension(50, 50));
        txt43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt43ActionPerformed(evt);
            }
        });

        txt53.setEditable(false);
        txt53.setBackground(new java.awt.Color(204, 153, 255));
        txt53.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txt53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt53.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt53.setPreferredSize(new java.awt.Dimension(50, 50));
        txt53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt53ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardLayout.createSequentialGroup()
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt70, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardLayout.createSequentialGroup()
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt70, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardLayout.createSequentialGroup()
                        .addComponent(txt67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("2");
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("7");
        jLabel15.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("3");
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("8");
        jLabel16.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("4");
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 30));

        btCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btCalcular.setFont(jLabel10.getFont());
        btCalcular.setText("Calcular!");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("5");
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Acertijo de las 8 reinas");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 30));

        lbl1.setFont(jLabel10.getFont());
        lbl1.setText("Columna de la primera reina:");

        txtCol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Arial Unicode MS", 0, 10)); // NOI18N
        label1.setText("Karen Arteaga (190161) y Uxia Velazquez (190940)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFila, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCol, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtFila)
                            .addGap(26, 26, 26)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(txtCol))
                        .addGap(9, 9, 9)))
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        label1.getAccessibleContext().setAccessibleName("Karen Arteaga (190161) y Uxia Velazquez (190940)");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaActionPerformed

    private void txt00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt00ActionPerformed

    private void txt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt10ActionPerformed

    private void txt01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt01ActionPerformed

    private void txt02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt02ActionPerformed

    private void txt03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt03ActionPerformed

    private void txt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt12ActionPerformed

    private void txt04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt04ActionPerformed

    private void txt05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt05ActionPerformed

    private void txt06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt06ActionPerformed

    private void txt07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt07ActionPerformed

    private void txt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt16ActionPerformed

    private void txt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt14ActionPerformed

    private void txt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt20ActionPerformed

    private void txt30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt30ActionPerformed

    private void txt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt21ActionPerformed

    private void txt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt22ActionPerformed

    private void txt32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt32ActionPerformed

    private void txt33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt33ActionPerformed

    private void txt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt23ActionPerformed

    private void txt24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt24ActionPerformed

    private void txt34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt34ActionPerformed

    private void txt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt25ActionPerformed

    private void txt26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt26ActionPerformed

    private void txt36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt36ActionPerformed

    private void txt27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt27ActionPerformed

    private void txt65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt65ActionPerformed

    private void txt66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt66ActionPerformed

    private void txt52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt52ActionPerformed

    private void txt76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt76ActionPerformed

    private void txt44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt44ActionPerformed

    private void txt45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt45ActionPerformed

    private void txt67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt67ActionPerformed

    private void txt46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt46ActionPerformed

    private void txt47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt47ActionPerformed

    private void txt56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt56ActionPerformed

    private void txt54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt54ActionPerformed

    private void txt60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt60ActionPerformed

    private void txt70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt70ActionPerformed

    private void txt61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt61ActionPerformed

    private void txt62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt62ActionPerformed

    private void txt72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt72ActionPerformed

    private void txt40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt40ActionPerformed

    private void txt50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt50ActionPerformed

    private void txt63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt63ActionPerformed

    private void txt41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt41ActionPerformed

    private void txt64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt64ActionPerformed

    private void txt74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt74ActionPerformed

    private void txt42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt42ActionPerformed

    private void txt43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt43ActionPerformed

    private void txt53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt53ActionPerformed
    /**
     * método que resuelve el tablero inicializando una variable tipo
     * <code> Operaciones</code> con el numero de columna que haya escrito el usuario
     * 
     * @param evt al hacer click en el <code> btCalcular</code>
     */
    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:       
        for(int i=0; i<8; i++){
            for (int j=0; j<8; j++){
                tablero[i][j].setText("");              
            }
        }
        try{
            String texto= txtCol.getText();
            int columna = Integer.parseInt(texto)-1;
            texto= txtFila.getText();
            int fila = Integer.parseInt(texto)-1;
            Operaciones o= new Operaciones(columna, fila);
            Integer[] sol= o.obtenerColumnas();
            
            for (int i=0; i<8; i++){
                tablero[i][sol[i]].setText("Q");                      
            }
        }catch(Exception e){
            lbl.setText("Deben ser numeros del 1 al 8");
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void txtColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColActionPerformed

    /**
     * ejecutable
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Reinas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel board;
    protected javax.swing.JButton btCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txt00;
    private javax.swing.JTextField txt01;
    private javax.swing.JTextField txt02;
    private javax.swing.JTextField txt03;
    private javax.swing.JTextField txt04;
    private javax.swing.JTextField txt05;
    private javax.swing.JTextField txt06;
    private javax.swing.JTextField txt07;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt27;
    private javax.swing.JTextField txt30;
    private javax.swing.JTextField txt31;
    private javax.swing.JTextField txt32;
    private javax.swing.JTextField txt33;
    private javax.swing.JTextField txt34;
    private javax.swing.JTextField txt35;
    private javax.swing.JTextField txt36;
    private javax.swing.JTextField txt37;
    private javax.swing.JTextField txt40;
    private javax.swing.JTextField txt41;
    private javax.swing.JTextField txt42;
    private javax.swing.JTextField txt43;
    private javax.swing.JTextField txt44;
    private javax.swing.JTextField txt45;
    private javax.swing.JTextField txt46;
    private javax.swing.JTextField txt47;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txt51;
    private javax.swing.JTextField txt52;
    private javax.swing.JTextField txt53;
    private javax.swing.JTextField txt54;
    private javax.swing.JTextField txt55;
    private javax.swing.JTextField txt56;
    private javax.swing.JTextField txt57;
    private javax.swing.JTextField txt60;
    private javax.swing.JTextField txt61;
    private javax.swing.JTextField txt62;
    private javax.swing.JTextField txt63;
    private javax.swing.JTextField txt64;
    private javax.swing.JTextField txt65;
    private javax.swing.JTextField txt66;
    private javax.swing.JTextField txt67;
    private javax.swing.JTextField txt70;
    private javax.swing.JTextField txt71;
    private javax.swing.JTextField txt72;
    private javax.swing.JTextField txt73;
    private javax.swing.JTextField txt74;
    private javax.swing.JTextField txt75;
    private javax.swing.JTextField txt76;
    private javax.swing.JTextField txt77;
    private javax.swing.JTextField txtCol;
    private javax.swing.JTextField txtFila;
    // End of variables declaration//GEN-END:variables
}
